name: Managed configuration tests

run-name: >-
  ${{ inputs.release_tag
      && format('Managed configuration tests [{0}]', inputs.release_tag)
      || github.workflow }}

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to identify this run for report-portal'
        type: string
        default: ''
        required: false
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  managed-configuration:
    permissions:
      contents: read
    uses: ./.github/workflows/managed-configuration-template.yaml
    secrets: inherit
