name: Managed configuration tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  managed-configuration:
    permissions:
      contents: read
    uses: ./.github/workflows/managed-configuration-template.yaml
    secrets: inherit
